# Human Tasks:
# 1. Ensure the 'logging' namespace exists before applying this configuration
# 2. Verify network policies allow traffic to port 5601
# 3. Configure ingress or load balancer if external access is needed
# 4. Review and adjust resource quotas for the logging namespace

# Addresses requirements:
# - Log Management (5.5.1 DevOps Tools): ELK Stack implementation for centralized log management
# - System Monitoring (3.2.2 Backend Service Architecture): Support Services including logging visualization and management
# - Monitoring Infrastructure (8.1 Deployment Environment): Production monitoring and logging infrastructure deployment

# Kubernetes API version: v1 (compatible with k8s 1.24+)
apiVersion: v1
kind: Service

# Service metadata including name and namespace
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
    service: logging

# Service specification
spec:
  # Select pods with label app=kibana
  selector:
    app: kibana
  
  # Define service ports
  ports:
    # HTTP port for Kibana web interface
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
  
  # Service type ClusterIP for internal access only
  type: ClusterIP