# Human Tasks:
# 1. Verify metrics-server is installed and running in the cluster
# 2. Configure custom metrics if needed beyond CPU/Memory
# 3. Review and adjust scaling thresholds based on production load patterns
# 4. Set up alerts for scaling events monitoring
# 5. Configure cluster autoscaler to handle pod scaling demands

# Kubernetes HPA v2 API
# Requirement: Auto-scaling - CPU/Memory based scaling using Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: founditure-backend-hpa
  namespace: prod
  labels:
    app: founditure-backend
    tier: backend
  annotations:
    description: "HPA configuration for Founditure backend service"
spec:
  # Reference to the deployment to scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: founditure-backend
  
  # Requirement: Application Tier Scaling - Auto-scaling (2-20 nodes) for production environment
  minReplicas: 2
  maxReplicas: 20
  
  # Scaling metrics configuration
  metrics:
    # Requirement: Auto-scaling - CPU utilization based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
    # Requirement: Auto-scaling - Memory utilization based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  
  # Scaling behavior configuration
  behavior:
    # Scale up behavior
    scaleUp:
      # Stabilization window to prevent rapid scaling
      stabilizationWindowSeconds: 60
      # Scaling policies
      policies:
        - type: Pods
          value: 2          # Maximum number of pods to add per scale action
          periodSeconds: 60 # How often scaling can occur
    
    # Scale down behavior
    scaleDown:
      # Longer stabilization window for scale down to prevent thrashing
      stabilizationWindowSeconds: 300
      # Scaling policies
      policies:
        - type: Pods
          value: 1          # Maximum number of pods to remove per scale action
          periodSeconds: 120 # How often scaling can occur